CC = gcc
CFLAGS = -I../compartido/src -Wall
LIBS = -lcommons -lpthread

SRCS = src/cpu.c ../compartido/src/conexiones.c
OBJ = bin/cpu

all: bin
	$(CC) $(SRCS) -o $(OBJ) $(CFLAGS) $(LIBS)

bin:
	mkdir -p bin

clean:
	rm -rf bin

